### ISSUE TITLE
Dependencies 

### ISSUE THREAD

**Issue by Gavin-Holt** [CDSoft/upp#1]
Hi

This looks very attractive. The syntax for macros is very clean and fits nicely in a markdown file.

Q1. Which versions of Lua will this run with? 

- Lua5.1 ?
- Lua5.2 ?
- Lua5.3 ?
- Lua5.4 ?
- Luajit ?

Q2. Are there dependencies on UNIX/Linux? 

- I am a windows 10 PC user and see a call to "realpath" - this is not on my path?

Q3. Is there any chance of a binary distribution for simplicity?

- My aim is to pipe Upp into MMD e.g. UPP.exe myfile.MD | Mutimarkdown.exe 

Kind Regards Gavin Holt

**Comment by CDSoft** [comment]
Hello,

Q1. upp has been tested with Lua 5.4.

Q2. realpath should be the only dependency and it makes upp not portable. But I'm not sure that path names (especially path separators) are correctly used in Windows.

Q3. I can provide an executable containing upp.lua and a Lua interpretor. But without this you can still use it in a pipe: `lua upp.lua myfile.md | multimarkdown`

I'll try to update upp to remove the dependency to realpath and build a windows executable containing the Lua interpretor (I can make a windows executable on Linux with mingw and test it with wine, but I may need your help to check it actually works on Windows).

**Comment by CDSoft** [comment]
I've pushed some fixes. realpath is no longer needed, windows path should be correctly handled and `upp.exe` contains a Lua interpretor:
- [upp.exe](http://cdelord.fr/upp/upp.exe)

**Comment by Gavin-Holt** [comment]
Hi

Many thanks. I will enjoy exploring.

Kind Regards Gavin Holt

**Comment by Gavin-Holt** [comment]
Hi,

Really enjoying upp.exe. I have tested with WindowsTM 20H2 with no problems (test.md attached).

Q1. When/how would I use the function called upp?

Q2. When/how would I use the function called sh?
It will pass a command line to WindowTM (e.g. "Notepad") - but this seems to crash the pipeline into multimarkdown. For console based programs is there a way to read in the output? 

Q3. Would LFS be a good addition to upp.exe. I cannot find any pre-compiled binary libraries for Lua54! 

Kind Regards Gavin Holt

[test_gmh.md](https://github.com/CDSoft/upp/files/7638050/test_gmh.md)

**Comment by Gavin-Holt** [comment]
Hi,

Just wanted to say how much I am enjoying upp.exe with multimarkdown6.exe. Work to date below with a pdf attached of the output on my system. 

Other who "think" in Lua may find this interesting and once I have finished exploring I was going to post [@ Lua-l](http://www.lua.org/lua-l.html) please let me know if there are errors.

Many thanks

Kind Regards Gavin Holt 

```
# Combining MultiMarkdown with Upp

## Introduction

Markdown has many advantages including native readability and significant "_value added_" 
for the user after rendering. A Lua based pre-processor adds computability to the work-stream 
- with interesting possibilities.

## Brief overview of Upp

[Upp](http://christophe.delord.free.fr/upp/) combines a $(_VERSION) VM with some nice 
clean syntax to embed code, import library code and insert values:

* Insert values with $\() e.g.

    $\( _VERSION )

* Include text for processing uses io.open:read("a") 

    $\( include([[file_name]])      )

* Embed code with :() e.g.

    :\( Text  = "Hello World"       )

* Load Lua scripts

    :\( require( [[script_name]]    ))<br>
    
    :\(  import( [[script_name]]    ))<br>
    
    :\(  dofile( [[file_name]]      ))<br> 


* Escape characters with \\ 


## Brief overview of Lua

The name is Portuguese for Moon (i.e. It's not an acronym - LUA is wrong). 
Lua's over-riding philosophy is to provide the basics, and allow you to build what you need 
- "batteries not included". The core and standard libraries are easily memorized. 

:(
    t = {}
    for i,v in pairs(_G) do
        if type(v)=="function" then
            table.insert(t,i)
        end
    end  
    table.sort(t)

    libs = {}  
    for i,v in pairs(_G) do
        if type(v)=="table" and i~="_G" then
            libs[i]=v
        end
    end

    for i,v in pairs(libs) do
        for k,j in pairs(v) do
            if type(j)=="function" then
                table.insert(t,i.."."..k)
            end
        end
    end

)

<div style="margin: 35px; columns: 4;">
$(table.concat(t,"<br>"))
</div>

Some functions seem so obvious you wonder how they have been left out (splitting
a string comes to mind), but Lua caters for edge cases where an imposed 
implementation may be unhelpful. Most users have their own little libraries of 
"_extensions_" e.g:
:(
    t = {}
    for i,v in pairs(_G) do
        if type(v)=="function" then
            t[i]=1
        end
    end  

    libs = {}  
    for i,v in pairs(_G) do
        if type(v)=="table" and i~="_G" then
            libs[i]=v
        end
    end

    for i,v in pairs(libs) do
        for k,j in pairs(v) do
            if type(j)=="function" then
                t[i.."."..k]=1
            end
        end
    end

    require("extensions")
    e = {}
    for i,v in pairs(_G) do
        if type(v)=="function" then
            if t[i]==1 then

            else
                table.insert(e,i)
            end
        end
    end
    table.sort(e)

    libs = {}  
    for i,v in pairs(_G) do
        if type(v)=="table" and i~="_G" then
            libs[i]=v
        end
    end

    for i,v in pairs(libs) do
        for k,j in pairs(v) do
            if type(j)=="function" then
                if t[i.."."..k]==1 then

                else
                    table.insert(e,i.."."..k)
                end
            end
        end
    end
)
<div style="margin: 35px; columns: 4;">
$(table.concat(e,"<br>"))
</div>

### Additional functions

Upp.exe also contains some additional functions not visible in _G:
:( 
u = {
"values",
"keys",
"items",
"map",
"filter",
"range",
"clone",
"concat",
"merge",
"sort",
"uniq",
"dirname",
"basename",
"noext",
"join",
"prefix",
"postfix",
"upp",
"sh",
})
<div style="margin: 35px; columns: 4;">
$(table.concat(u,"<br>"))
</div>

### Using saved scripts

* The Lua require function will load scripts which will be active from that point forward 
- even in distant "chunks". Required files are added to the global state. Lua will search
the package.path for scripts.
    :(require("extensions"))
    $("Date Stamp = "..os.datestamp())

* The Upp import function seems to be identical to the require function??
    :(import("test2.lua") )
    $("test2.lua says : "..test2())

* The Lua dofile function may return values (which could be functions) which will be active 
from that point forward - even in distant "chunks". Dofile searches relative to the current 
script and will accept a root path (e.g. [[\MyProfile\Code\Lua\Test.lua]]).  
Dofile chunks can reference variables previously assigned with the _G prefix 
(see boiler plate text below). New variables/functions are local, items not returned are lost.
    :(test = dofile([[test.lua]]))
    $("test.lua says : "..test())

## Computationally enhanced documents

### Enhanced Prose

* Arbitatry calculations

    £120 (£$(120*1.3) inc. Tax)
    
* Boiler plate text
    :( -- define some globals, then call boiler plate script
    _G.Buyer = "Gavin Holt"
    _G.Seller = "Tom Jones"
     )
    $(dofile([[boiler_plate.lua]]))

* Citations from PubMed downloaded nbib files
    :( import("ref") )
    * Test1 $(ref("test1")) routine
    * Test2 $(ref("test2")) single author
    * Test3 $(ref("test3")) long multiline title and multiple PT strings
    
### Manipulate Numbers

Have you every wanted an alternative to the spreadsheet? 

### Manipulate Data

Small databases defined in serialized Lua tables allow data CRUD. 

## Self documenting code

This is the opposite of a pre-prossesor; the source is executed and the documentation regenerated.

## Literate Programming

### Definition

Coding should be as refined as literature, with beautiful expositions of intent and method.

## Bibilography
    
```

[mmd+upp.pdf](https://github.com/CDSoft/upp/files/7723702/mmd%2Bupp.pdf)

**Comment by CDSoft** [comment]
Hello,

Thanks for your feedback.

> Q1. When/how would I use the function called upp?

I'm not sure the Lua function `upp` is really useful for the end user. It expands macros in a string but this is now automatic when files are included for instance.

> Q2. When/how would I use the function called sh?
> It will pass a command line to WindowTM (e.g. "Notepad") - but this seems to crash the pipeline into multimarkdown. For console based programs is there a way to read in the output?

`sh` uses io.popen to execute a command and insert the output of the command into the document. Notepad is not the kind of command to execute with `sh`. You can use `sh` to execute scripts or programs that will generate a part of the document. e.g.:

    This document has been produced on $(sh "uname -a")

> Q3. Would LFS be a good addition to upp.exe. I cannot find any pre-compiled binary libraries for Lua54!

The binary is made with luastatic and just includes upp.lua. I would say that "compiling" upp.lua with custom libraries could be part of another project. The current philosophy is rather to deliver a plain Lua script.
This may be an issue for https://github.com/CDSoft/luapack

I'll comment you document in another message (too busy now ;-)

**Comment by CDSoft** [comment]
```
Upp.exe also contains some additional functions not visible in _G:
:( 
u = {
"values",
"keys",
"items",
"map",
"filter",
"range",
"clone",
"concat",
"merge",
"sort",
"uniq",
"dirname",
"basename",
"noext",
"join",
"prefix",
"postfix",
"upp",
"sh",
})
```

In fact additional upp functions are:

- input_files
- output_file
- die
- import
- include
- when
- map
- filter
- range
- concat
- merge
- dirname
- basename
- join
- sh
- prefix
- postfix
- atexit
- emit

I've updated the documentation : http://christophe.delord.free.fr/upp/index.html#builtin-macros

```
* The Upp import function seems to be identical to the require function??
    :(import("test2.lua") )
    $("test2.lua says : "..test2())
```

There is a small difference between `import` and `require`. Import keep track of the imported scripts to generate make dependencies. Otherwise they both load a Lua module. I'm thinking of removing `import` and use the `package` module to list scripts loaded by `require`.

BTW you can write constant text outside Lua code: `$("test2.lua says : "..test2())` <=> `test2.lua says : $(test2())`

```
    :( -- define some globals, then call boiler plate script
    _G.Buyer = "Gavin Holt"
    _G.Seller = "Tom Jones"
     )
```

Scripts are run in the global environment (`_G`) so this should be equivalent to:

```
    :( -- define some globals, then call boiler plate script
    Buyer = "Gavin Holt"
    Seller = "Tom Jones"
     )
```

Nice work ;-)
