### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by Gavin-Holt** [CDSoft/upp#2]
Hi,

I am having troubles with the Lua require function. My library of extensions include some functions added to standard libraries (e.g. string.trim() string.split() ) - these work after require("extensions"). 

Other functions normally (Lua5.1) added to the global environment are not working. If I use your import function then these global functions do work. 

Also I tried removing the _G prefix in my example of boiler plate text and it failed. 

    :( -- define some globals, then call boiler plate script
    _G.Buyer = "Gavin Holt"
    _G.Seller = "Tom Jones"
     )
    $(dofile([[boiler_plate.lua]]))

Boiler_plate.lua is below:

    local t = {
        "For the duration of the contract party one ($Seller) and party "..
        "two ($Buyer) will agree to abide by the decisions of the arbiter.",
        "Any deviation from the contract by either party will be deemed as "..
        "early contract termination and the contracted penalties will be applied.",
        "There is no appeal under these circumstances.",

    }

    return table.concat(t," "):gsub("$Seller",Seller):gsub("$Buyer",Buyer)

I am not a Lua expert but suspect this is to do with alternate environments?

Kind Regards Gavin Holt

**Comment by CDSoft** [comment]
The upp environment is unnecessarily complicated and does not work well.
I'll use _G for the document and local functions for the implementation of upp.

**Comment by CDSoft** [comment]
Now you can write:

```
:(  -- define some globals, then call boiler plate script
    Buyer = "Gavin Holt"
    Seller = "Tom Jones"
 )
$(dofile "boiler_plate.lua")
```
or
```
:(  -- define some globals, then call boiler plate script
    Buyer = "Gavin Holt"
    Seller = "Tom Jones"
 )
$(require "boiler_plate")
```

Note: no `.lua` extension with `require`.

And `boiler_plate.lua` is:

```lua
local t = {
    "For the duration of the contract party one ($Seller) and party "..
    "two ($Buyer) will agree to abide by the decisions of the arbiter.",
    "Any deviation from the contract by either party will be deemed as "..
    "early contract termination and the contracted penalties will be applied.",
    "There is no appeal under these circumstances.",

}

return table.concat(t," "):gsub("$Seller",Seller):gsub("$Buyer",Buyer)
```

or even:

```lua
return [[
For the duration of the contract party one $(Seller) and party
two $(Buyer) will agree to abide by the decisions of the arbiter.

Any deviation from the contract by either party will be deemed as
early contract termination and the contracted penalties will be applied.

There is no appeal under these circumstances.
]]
```

This simple example can be simplified by importing a text file:

Main document:
```
:(  -- define some globals, then call boiler plate script
    Buyer = "Gavin Holt"
    Seller = "Tom Jones"
 )
$(include "boiler_plate.txt")
```

`boiler_plate.txt`:
```
For the duration of the contract party one $(Seller) and party
two $(Buyer) will agree to abide by the decisions of the arbiter.

Any deviation from the contract by either party will be deemed as
early contract termination and the contracted penalties will be applied.

There is no appeal under these circumstances.
```

**Comment by Gavin-Holt** [comment]
Hi,

Many thanks with the new upp.exe this all works at my end. 

Kind Regards Gavin Holt
